### ISSUE TITLE
How do I use this?

### ISSUE THREAD

**Issue by kurtlippert** [labd/commercetools-mock-server#2]
Hey all!

Like the question says, how should we use mock server once we have it running locally? Could you all provide some more detailed instructions and examples?

Thanks!

**Comment by davidweterings** [comment]
The main use of this repo (at least for Lab Digital) is to run the Commercetools Terraform Provider unit tests in our CI pipeline: https://github.com/labd/terraform-provider-commercetools/blob/master/.azure-pipelines/main.yml

Basically, you run the docker container:

`
docker run -p 8989:8989 labdigital/commercetools-mock-server
`

And then you set the configure your commercetools client auth/api url to talk to http://localhost:8989

It uses our Python SDK https://github.com/labd/commercetools-python-sdk Please note that not every action is implemented, and some actions don't work 100% the same as a real Commercetools instance. It's worked pretty well for us so far though.

**Comment by kurtlippert** [comment]
hey david,

thanks for the reply!

How would you configure your `Client()` in python

**Comment by davidweterings** [comment]
As follows:

First allow http requests for Oauth (should normally require https):
`export OAUTHLIB_INSECURE_TRANSPORT=1` 

Then in Python, note only the url, token_url are important, the rest can be random values.

```
from commercetools import Client

client = Client(project_key="unittest", client_id="unittest", client_secret="unittest", token_url="http://localhost:8989/oauth/token", url="http://localhost:8989", scope="manage_project:todo")
```
